### ISSUE TITLE
Test with updated version, Uwazi v1.3

### ISSUE THREAD

**Issue by fititnt** [fititnt/uwazi-docker#16]
Uwazi v1.3 was released yesterday: https://github.com/huridocs/uwazi/releases/tag/v1.3

**Comment by fititnt** [comment]
Humm, the v1.3 have one more dependency, added on this commit 

https://github.com/huridocs/uwazi/commit/5f15cc1b9845424bcf2b2e993dce1026bf9507e8

**Comment by fititnt** [comment]
And NodeJs 8.11.x

**Comment by fititnt** [comment]
I'm not sure if the default version of `poppler-utils` will be 0.67.0 or more from the `FROM node:8-slim` (https://github.com/nodejs/docker-node/blob/526c6e618300bdda0da4b3159df682cae83e14aa/8/slim/Dockerfile) on the uwazi-docker Dockerfile.

So if possibly will work for a fast release, but think will need some additional testing from more people.

But the release https://github.com/fititnt/uwazi-docker/releases/tag/v1.2.0-beta.2 should still work.

**Comment by fititnt** [comment]
As reference, node:8-slim will load the version 0.26.5-2+deb8u4 (refs https://packages.debian.org/pt-br/jessie/poppler-utils) from Sat Sep 27, 2014. 

poppler-0.68 was released on Sun Aug 19, 2018 (https://poppler.freedesktop.org/releases.html). So the developer used a pretty recent version, maybe with very good reason

**Comment by txau** [comment]
@fititnt if admin/admin still works, you are probably using an older database.

**Comment by fititnt** [comment]
@txau good to know. In the next days I will review the full initialization at https://github.com/fititnt/uwazi-docker/blob/master/docker-entrypoint.sh.

Also, instead of blank-state data for a production build, what command allows import some demonstration dataset? `yarn download-mongo-prebuilt`?

**Comment by txau** [comment]
@fititnt we need to improve this demo dataset, nevertheless we use this repo for functional testing:

https://github.com/huridocs/uwazi-fixtures

If you checkout this repo inside your Uwazi directory (it's already added to the .gitignore) and run "yarn fixtures", it will load and index a collection of ~300 docs and entities with some metadata set.

**Comment by fititnt** [comment]
@txau Nice to know. Also there is a lot of data there!

Not sure if will add a demo flag to startup of document, but if have to, probably will reuse some of these datasets

**Comment by txau** [comment]
Related: https://github.com/huridocs/uwazi/issues/1941

I hope we can provide a richer demo sometime soon. That data you are seeing is coming from our very first Uwazi-based project: https://sidh.cejil.org
