### ISSUE TITLE
make elasticsearch  behave

### ISSUE THREAD

**Issue by vasyugan** [fititnt/uwazi-docker#35]
Today I found that the elasticsearch container has brought down our server with 32gb ram two times in a row. I don't know what the ulimit memlock -1 means exactly that you added to the elasticsearch services, the docker documentation does not explain. Does it mean that you lift all limitations? Because I'd rather see Uwazi fail than seeing the entire server it runs on. And that's what I have seen two times today. For the time being, I have stopped uwazi and will investigate the situation.

**Comment by fititnt** [comment]
Good to know. Make some updates on this issue to see what we could improve here.

**Comment by vasyugan** [comment]
I am not sure that it really was elasticsearch that ate up all the memory. But in any case, this ulimit memlock -1 looks a bit spooky to me. Isn't it lifting all limitations on memory allocation for the process? It is needed?

**Comment by fititnt** [comment]
Ah, the `ulimit` config from docker comes from this documentation of Docker on Elastic Search to run in production, see <https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html>.

But one question here is... why is your application crashing? Is because of run out of memory? Or is other problem? This is strange. In special if you are not importing a massive amount of documents.

**Comment by vasyugan** [comment]
Am 09.11.18 um 00:19 schrieb Emerson Rocha Luiz:
>
> Ah, the |ulimit| config from docker comes from this documentation of
> Docker on Elastic Search to run in production, see
> https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html.
>
> But one question here is... why is your application crashing? Is
> because of run out of memory? Or is other problem? This is strange. In
> special if you are not importing a massive amount of documents.
>
Actually, it is not the application, that has been crashing but the
whole server has been hanging and had to be rebooted. Too many
processes, out of memory. But we are not certain that it is the fault of
Java,  it might also have been sa-learn, because of a massive spam
learning job

Johannes

**Comment by fititnt** [comment]
@vasyugan I will close this issue for now. Please, if this seems to be a problem of docker-uwazi or something we can improve, just open it again.
