### ISSUE TITLE
Instructions or mechanism for upgrading

### ISSUE THREAD

**Issue by vasyugan** [fititnt/uwazi-docker#43]
I just saw that Uwazi 1.5 is out. Upgrading on a plain installation is easy. But on docker it seems to involve removing the image and building a new one, or is there a better way?

**Comment by fititnt** [comment]
I'm a bit busy with other projects to give imediate response on the Uwazi 1.5, but we have (not yet) merged PR here about this issue. Maybe we could discuss there https://github.com/fititnt/uwazi-docker/pull/39.

But if the Uwazi 1.5 made extra changes on the operational system, this would not be just a simple upgrade.
