### ISSUE TITLE
Jessie no longer works

### ISSUE THREAD

**Issue by vasyugan** [fititnt/uwazi-docker#44]
The jessie node image no longer gets its updates, obviously, Debian has pulled the plug on jessie. Therefore I am now rebuilding with stretch

**Comment by fititnt** [comment]
@vasyugan look at this last commit https://github.com/fititnt/uwazi-docker/commit/3002337c2600851791ad5974aa1c359ef68a5ee0

Can you confirm with me that we can change the `FROM node:8-jessie` to `FROM node:8-stretch` without major errors?

If yes, you can just make a pull request, with only this change

**Comment by fititnt** [comment]
Ok, I will close this based on your commentary at https://github.com/fititnt/uwazi-docker/commit/3002337c2600851791ad5974aa1c359ef68a5ee0#commitcomment-32931536, @vasyugan .

If need, can just re-open this issue.
