### ISSUE TITLE
Error when saving collection: Transaction numbers are only allowed on a replica set member or mongos

### ISSUE THREAD

**Issue by magereanu** [fititnt/uwazi-docker#53]
I get this error ,  Transaction numbers are only allowed on a replica set member or mongos

How do i fix???

![image](https://github.com/fititnt/uwazi-docker/assets/17160815/9dc22fa7-b788-4343-937b-9688f9f8435f)

**Comment by fititnt** [comment]
Oh, another user! I was not aware more people are using (over the years, few people commented here). Ok. There's demand.

However, this is the same issue as the one reported by @hakkiunlu on https://github.com/fititnt/uwazi-docker/issues/52 **(I will mark as duplicated, then ask you to comment in the other issue). You can still comment here (and others might also open other issues) but I think we should comment on the #52.**

I do know what's wrong, and is a more specific problem than the pinned issue https://github.com/fititnt/uwazi-docker/issues/48 and while obviously is theoretical possible do with containers, on a quick look, I did not found an simpler fix. Also, our solution to the problem might be similar to this another issue on the upstream repository (https://github.com/huridocs/uwazi/issues/5633).
